### ISSUE TITLE
Add rounding to floating point numbers

### ISSUE THREAD

**Issue by roysjosh** [Jc2k/aiohomekit#211]
Request from an HA user: https://community.home-assistant.io/t/eve-energy-smart-plug-thread-over-homepod-mini/476282/4?u=lambdafunction

![image](https://user-images.githubusercontent.com/601535/197586491-001ed2ac-c016-4001-b894-a2bb9884ede8.png)

**Comment by Jc2k** [comment]
In general we've said it's a front end issue because some users will want .1, some will want .01, etc. not a decision we should take at this level and probably not one we can take in the integration. The same applies to a lot of the non homekit passive Bluetooth sensors - and don't really want to duplicate rounding in every integration.

Ideally the front end would just round for us.

Don't have too strong of an opinion (I have the same grim looking dashboards in my ha and i definitely don't like it), but not sure what the best way forward is.

**Comment by roysjosh** [comment]
Good point, front end would be a better place, probably near the "units" selection.
